M48
; DRILL file {KiCad 9.0.4-9.0.4-0~ubuntu22.04.1} date 2025-12-08T20:54:37+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-08T20:54:37+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-9.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X125.06Y-117.6
X130.84Y-117.6
T2
X166.83Y-79.2
X166.83Y-82.2
M30
